recipeVersion: 1.0.0-alpha.1
applications:
  - name: hackathon-cpp-app
    containers:
      - name: sample-app 
        image: ghcr.io/liciniomendes-vestas/hackathon-2025-cplusplus-samples/sample-app:master
