recipeVersion: 1.0.0-alpha.1
applications:
  - name: hackathon-cpp-app
    containers:
      - name: sample-app 
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/hackathon-2025-cplusplus-samples/sample-app:sha-060881b
