recipeVersion: 1.0.0-alpha.1
applications:
  - name: hackathon-cpp-app
    containers:
      - name: sample-app 
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/hackathon-2025-cplusplus-samples/sample-app:master
  - name: hackathon-database
    containers:
      - name: database
        image: registry-pminds.ns-azweu-stg.vks.vestas.net/hackathon-2025-cplusplus-samples/sample-db:master
        volumes:
          - name: data
            path: /var/lib/postgresql/data
            size: 200Mi
    ports:
      - port: 5432
